# Generated by Django 2.2.7 on 2019-11-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
            ],
        ),
    ]
